const doctorSecreteKey="fjslfoiwurerfksfdkljsalkfwruiojflskuoawrklsfksaj";
const patientSecreteKey="jfdsrweuiosknfslkjowiermnfsjoiwrwnlksnfksjflkasj";


module.exports={doctorSecreteKey,patientSecreteKey}