name: "Workflow for Node and react app"

on:
    push:
        branches:
            - main

jobs:
    Checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

       
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./portfolio/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
            - name: Connect to EC2 instance
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_PUBLIC_IP }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                port: ${{ secrets.EC2_SSH_PORT }}
                script: |
                    echo "Connected to EC2 instance"
                    sudo docker ps -q --filter "publish=80" | xargs -r sudo docker stop
                    sudo docker ps -q --filter "publish=80" | xargs -r sudo docker rm
                    sudo docker stop portfolio || true # Stop all running containers, ignore errors if there are none
                    sudo docker rm portfolio || true    # Remove all containers, ignore errors if there are none
                    sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio
                    sudo docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/portfolio